
services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  user-service:
    build: ./userservice
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    image: user-service


  parking-service:
    build: ./parkingservice
    container_name: parkingdonservice
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

  booking-service:
    build: ./bookingservice
    container_name: booking-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis
    ports:
      - "6379:6379"
